site_name: Mathsforall
site_url: https://jimmyzhan.github.io/math-portfolio

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - header.autohide
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - content.cards

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - toc:
      permalink: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - styles/extra.css

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_buld_date: true

nav:
  - Home: index.md 
  - Notes:
      - Functions:
        - Determining the oblique asymptote solely on the graph: notes/Existence_of_OA_discussion.md 
        - Discovery of power-exponential functions: notes/The_function_with_no_graph.md
      - Multivariable Differential Calculus:
        - The nature of dot product: notes/Why_Dot_Product.md
        - Proof of universal equation of curvature with parameter t: notes/Curvature_time_parametrization_proof.md
      - Algebraic Topology:
        - Proof of definition of open sets in metric space: notes/proof_open_interior.md
        - Proof of definition of closed sets in metric space: notes/proof_closed_interior.md
      - Proof of The Basel Problem:
        - Proof of Basel Problem by Leonhard Euler: notes/basel_problem_euler.md
  - Projects:
      - Modification of existing numerical optimization methods in the application of logistic regression: projects/Optimization.md



